// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnxF4iALMEWO_U_PFDSz700fLW1WN9SAc',
    appId: '1:66769815908:web:de45089b08fa198f101271',
    messagingSenderId: '66769815908',
    projectId: 'papkuas-expensetrack',
    authDomain: 'papkuas-expensetrack.firebaseapp.com',
    storageBucket: 'papkuas-expensetrack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq1VM31bAUQEkRQO4Ocb0-C39P1q5TKzM',
    appId: '1:66769815908:android:31ee9e704e7157e2101271',
    messagingSenderId: '66769815908',
    projectId: 'papkuas-expensetrack',
    storageBucket: 'papkuas-expensetrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaSLeJyIwWVjcRswKPt0sLLGmgfSqVp1o',
    appId: '1:66769815908:ios:526bac5272ff4a57101271',
    messagingSenderId: '66769815908',
    projectId: 'papkuas-expensetrack',
    storageBucket: 'papkuas-expensetrack.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaSLeJyIwWVjcRswKPt0sLLGmgfSqVp1o',
    appId: '1:66769815908:ios:526bac5272ff4a57101271',
    messagingSenderId: '66769815908',
    projectId: 'papkuas-expensetrack',
    storageBucket: 'papkuas-expensetrack.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnxF4iALMEWO_U_PFDSz700fLW1WN9SAc',
    appId: '1:66769815908:web:6017101337edd22b101271',
    messagingSenderId: '66769815908',
    projectId: 'papkuas-expensetrack',
    authDomain: 'papkuas-expensetrack.firebaseapp.com',
    storageBucket: 'papkuas-expensetrack.firebasestorage.app',
  );

}